[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
protocol = "9bGeadnqYTmBhDTxA9KLLgiiY6k33fmsi1vm99AV23mE"

[programs.localnet]
protocol = "9bGeadnqYTmBhDTxA9KLLgiiY6k33fmsi1vm99AV23mE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
create = "yarn run ts-node scripts/create.ts"
deploy-init = "anchor deploy && yarn run ts-node scripts/initialize.ts"
init = "yarn run ts-node scripts/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
program = "program_dumps/pyth-solana-receiver.so"

[[test.genesis]]
address = "pythWSnswVUd12oZpeFP8e9CVaEqJg25g1Vtc2biRsT"
program = "program_dumps/pyth-price-feed.so"

[[test.genesis]]
address = "HDwcJBJXjL9FpJ7UBsYBtaDjsBUhuLCUYoz3zr8SWWaQ"
program = "program_dumps/wormhole.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "DBE3N8uNjhKPRHfANdwGvCZghWXyLPdqdSbEW2XFwBiX"

[[test.validator.clone]]
address = "6UxPR2nXJNNM1nESVWGAf8NXMVu3SGgYf3ZfUFoGB9cs"

[[test.validator.clone]]
address = "6B23K3tkb51vLZA14jcEQVCA1pfHptzEHFA93V5dYwbT"

[[test.validator.clone]]
address = "9vNb2tQoZ8bB4vzMbQLWViGwNaDJVtct13AGgno1wazp"

[[test.validator.clone]]
address = "5gxPdahvSzcKySxXxPuRXZZ9s6h8hZ88XDVKavWpaQGn"

[[test.validator.clone]]
address = "DaWUKXCyXsnzcvLUyeJRWou8KTn7XtadgTsdhJ6RHS7b"

[[test.validator.clone]]
address = "2t8eUbYKjidMs3uSeYM9jXM9uudYZwGkSeTB4TKjmvnC"
